[package]
name = "actix-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
actix-web = { version = "4.4.0", features = ["macros"] }
serde = { version = "1.0.209", features = ["derive"] }
surrealdb = "2.1.2"
thiserror = "1.0.63"
